# Generated by Django 5.2.16 on 2026-07-09 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests_from', models.PositiveIntegerField()),
                ('guests_to', models.PositiveIntegerField(blank=True, help_text="Null means 'and above'.", null=True)),
                ('price_per_guest', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['guests_from'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('layout_hint', models.CharField(choices=[('venue', 'Venue-like (capacity & location matter)'), ('service', 'Service-like (portfolio & media matter)')], default='service', max_length=10)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price_currency', models.CharField(choices=[('EUR', 'Euro'), ('MKD', 'Denar')], default='EUR', max_length=3)),
                ('price_type', models.CharField(choices=[('fixed', 'Fixed price'), ('per_guest', 'Per guest'), ('tiered_per_guest', 'Tiered per guest'), ('per_hour', 'Per hour'), ('starting_at', 'Starting at')], default='fixed', max_length=20)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Used for fixed / per_hour / starting_at.', max_digits=12, null=True)),
                ('price_per_guest', models.DecimalField(blank=True, decimal_places=2, help_text='Used for per_guest.', max_digits=10, null=True)),
                ('min_guest_count', models.PositiveIntegerField(blank=True, help_text='Billing floor: minimum guests billed regardless of turnout.', null=True)),
                ('min_capacity', models.PositiveIntegerField(blank=True, help_text='Booking floor: smallest event accepted.', null=True)),
                ('max_capacity', models.PositiveIntegerField(blank=True, help_text='Hard ceiling on guests.', null=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Category-specific attributes (e.g. style tags, has_parking).')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('categories', models.ManyToManyField(blank=True, related_name='offers', to='catalog.category')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
