# Generated by Django 5.2.17 on 2026-08-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='audience',
            field=models.CharField(choices=[('couple', 'Both / the couple'), ('bride', 'Bride'), ('groom', 'Groom')], default='couple', help_text='Drives the Bride/Groom quick filters.', max_length=10),
        ),
    ]
