# Generated by Django 5.2.17 on 2026-08-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_mk',
            field=models.CharField(blank=True, help_text='Macedonian display name.', max_length=140),
        ),
    ]
