# Generated by Django 5.2.17 on 2026-08-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_name_mk'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description_mk',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='name_mk',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
