# Generated by Django 5.2.17 on 2026-08-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name_mk',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='region',
            name='name_mk',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
