# Generated by Django 5.2.16 on 2026-07-09 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('business_type', models.CharField(choices=[('company', 'Company'), ('individual', 'Individual')], default='company', max_length=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending review')], default='active', max_length=10)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('categories', models.ManyToManyField(blank=True, related_name='vendors', to='catalog.category')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='locations.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('viber', models.CharField(blank=True, max_length=40)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=120)),
                ('facebook', models.CharField(blank=True, max_length=120)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='vendors.vendor')),
            ],
        ),
    ]
