# Generated by Django 5.2.17 on 2026-08-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='credit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='media',
            name='credit_url',
            field=models.URLField(blank=True),
        ),
    ]
