# Generated by Django 5.2.17 on 2026-08-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_media_credit_media_credit_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='credit_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
